### ISSUE TITLE
Can't contact LDAP server since version 1.5.9

### ISSUE THREAD

**Issue by aidygus** [Adldap2/Adldap2#189]
Version 1.5.8 works but when I run composer update to get the latest I get the following error in laravel 5.2 : 

```
AdldapException in Adldap.php line 376:
Bind to Active Directory failed. Either the LDAPs connection failed or the login credentials are incorrect. AD said: Can't contact LDAP server
```

And in the log I get : 

```
#0 /home/user/web/myapp/vendor/adldap2/adldap2/src/Adldap.php(400): Adldap\Adldap->bindUsingCredentials('', '', '@mds.ad.mycorp.com....')
#1 /home/user/web/myapp/vendor/adldap2/adldap2/src/Adldap.php(247): Adldap\Adldap->bindAsAdministrator()
#2 /home/user/web/myapp/vendor/adldap2/adldap2/src/Adldap.php(61): Adldap\Adldap->connect()
#3 /home/user/web/myapp/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(52): Adldap\Adldap->__construct(Array, Object(Adldap\Connections\Ldap), true)
#4 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Adldap\Laravel\AdldapServiceProvider->Adldap\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#6 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('adldap', Array)
#7 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('adldap')
#8 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(151): Illuminate\Container\Container->offsetGet('adldap')
#9 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(120): Illuminate\Support\Facades\Facade::resolveFacadeInstance('adldap')
#10 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(207): Illuminate\Support\Facades\Facade::getFacadeRoot()
#11 /home/user/web/myapp/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php(211): Illuminate\Support\Facades\Facade::__callStatic('users', Array)
#12 /home/user/web/myapp/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php(211): Adldap\Laravel\Facades\Adldap::users()
#13 /home/user/web/myapp/vendor/adldap2/adldap2-laravel/src/AdldapAuthUserProvider.php(43): Adldap\Laravel\AdldapAuthUserProvider->newAdldapUserQuery()
#14 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(353): Adldap\Laravel\AdldapAuthUserProvider->retrieveByCredentials(Array)
#15 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(314): Illuminate\Auth\SessionGuard->attempt(Array)
#16 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(275): Illuminate\Auth\SessionGuard->attemptBasic(Object(Illuminate\Http\Request), 'email', Array)
#17 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Auth/Middleware/AuthenticateWithBasicAuth.php(38): Illuminate\Auth\SessionGuard->basic()
#18 [internal function]: Illuminate\Auth\Middleware\AuthenticateWithBasicAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /home/user/web/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /home/user/web/myapp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 /home/user/web/myapp/server.php(21): require_once('/home/user/web...')
#41 {main}  
```

The latest adldap2/adldap2-laravel works with 1.5.8.

**Comment by stevebauman** [comment]
```php
#3 /home/user/web/myapp/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(52): Adldap\Adldap->__construct(Array, Object(Adldap\Connections\Ldap), true)
```

You have `auto_connect` enabled in your `adldap.php` configuration. If you disable it and connect manually you won't receive this error.
