### ISSUE TITLE
Not possible to connect to DC over SSL

### ISSUE THREAD

**Issue by MarcelLang** [Adldap2/Adldap2#368]
Hi,

I have some trouble getting the SSL connection to work. I have setup oure DC as a CA. In other clients the connection over SSL works fine and without certificate problems, but not with Adldap2. I think I may have overlooked something and asking for help.

Without SSL the connection works fine.

### Here is my code:

```
$config = [
  'account_suffix'        => '@xxx.intern',
  'domain_controllers'    => ['SRV-V-DC02.xxx.intern'],
  'base_dn'               => 'DC=xxx,DC=intern',
  'admin_username'        => 'Administrator',
  'admin_password'        => 'xxxxxxxxx',
  'use_ssl'               => true
];

require_once 'vendor/autoload.php';

$ad = new \Adldap\Adldap();
$ad->addProvider($config);

try {
   $provider = $ad->connect();
} catch (\Adldap\Exceptions\Auth\BindException $e) {

}

```
### The error message:

```

Fatal error:  Uncaught exception 'Adldap\Auth\BindException' with message 'Can't contact LDAP server' in ***PATH****\www\vendor\adldap2\adldap2\src\Auth\Guard.php:80
Stack trace:
#0 ***PATH****\www\vendor\adldap2\adldap2\src\Auth\Guard.php(94): Adldap\Auth\Guard->bind('Administrator', '*********', '', '')
#1 ***PATH****\www\vendor\adldap2\adldap2\src\Connections\Provider.php(210): Adldap\Auth\Guard->bindAsAdministrator()
#2 ***PATH****\www\vendor\adldap2\adldap2\src\Adldap.php(113): Adldap\Connections\Provider->connect(NULL, NULL)
#3 ***PATH****\www\index.php(18): Adldap\Adldap->connect()
#4 {main}
  thrown in ***PATH****\www\vendor\adldap2\adldap2\src\Auth\Guard.php on line 80
```

I would really appreciate some help,
thank you.

**Comment by stevebauman** [comment]
Hi @MarcelLang, try using the port `636`:

```php
$config = [
    '...',
    'port' => 636,
];

```

**Comment by MarcelLang** [comment]
I'm feeling realy stupid right now, its working flawlessly now.

Thank you for your help 👍

**Comment by stevebauman** [comment]
No problem! Glad you've resolved your issue :).
