### ISSUE TITLE
Struggle connecting

### ISSUE THREAD

**Issue by FredTheHomie** [Adldap2/Adldap2#402]
I have followed the guide, but I still have errors. Please note that I am a complete noob. Here is my `code:`

```
<?php

include (dirname(__FILE__) . "/src/Adldap.php");

use \Adldap\Adldap;

$config = [
    'domain_cotrollers' => [''],
    'base_dn'          => '',
    'admin_username'    => '',
    'admin_password'    => '',
];

$ad = new Adldap($config);

?>
```
This is the error I currently have:

> Fatal error: Interface 'Adldap\AdldapInterface' not found in C:\xampp\htdocs\SoftwareDatabase\src\Adldap.php on line 12

**Comment by stevebauman** [comment]
Hi @FredTheHomie, you need to install Composer to pull in the Adldap2 and it's dependencies. Non composer installations are not supported.

I'd heavily recommend reading up on some tutorials for composer to get started as it's the defacto standard for managing dependencies for PHP applications.

**Comment by FredTheHomie** [comment]
I did everything thus far following the guide. I did in fact use composer. I changed me code to this:

```
<?php

require 'vendor/autoload.php';

//include (dirname(__FILE__) . "/src/Adldap.php");

$config = [
    'domain_cotrollers' => ['ldap.mmu.ac.uk'],
    'base_dn'           => 'ou=mmu,dc=ad,dc=mmu,dc=ac,dc=uk',
    'admin_username'    => 'adbind@ad.mmu.ac.uk',
    'admin_password'    => 'Acc3ssmgmt',
    
    'port'              => 636,
];

$Adldap = new Adldap\Adldap($config);

?>
```
And now my error is:

> 

Fatal error: Uncaught Adldap\Configuration\ConfigurationException: Option 0 does not exist. in C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php:116 Stack trace: #0 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(146): Adldap\Configuration\DomainConfiguration->get(0) #1 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(94): Adldap\Configuration\DomainConfiguration->validate(0, 'ldap.mmu.ac.uk') #2 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(77): Adldap\Configuration\DomainConfiguration->set(0, 'ldap.mmu.ac.uk') #3 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Connections\Provider.php(75): Adldap\Configuration\DomainConfiguration->__construct(Array) #4 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Connections\Provider.php(50): Adldap\Connections\Provider->setConfiguration(Array) #5 C:\xampp\htdocs\S in C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php on line 116

**Comment by FredTheHomie** [comment]
I did use composer, I followed the guide. I just replaced this line:

`include (dirname(__FILE__) . "/src/Adldap.php");`

to

`require 'vendor/autoload.php';`

And now my errors are:


> Fatal error: Uncaught Adldap\Configuration\ConfigurationException: Option 0 does not exist. in C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php:116 Stack trace: #0 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(146): Adldap\Configuration\DomainConfiguration->get(0) #1 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(94): Adldap\Configuration\DomainConfiguration->validate(0, 'ldap.mmu.ac.uk') #2 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php(77): Adldap\Configuration\DomainConfiguration->set(0, 'ldap.mmu.ac.uk') #3 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Connections\Provider.php(75): Adldap\Configuration\DomainConfiguration->__construct(Array) #4 C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Connections\Provider.php(50): Adldap\Connections\Provider->setConfiguration(Array) #5 C:\xampp\htdocs\S in C:\xampp\htdocs\SoftwareDatabase\vendor\adldap2\adldap2\src\Configuration\DomainConfiguration.php on line 116

**Comment by stevebauman** [comment]
It looks like you're setting an incorrect configuration option. Can you post your updated config array with sensitive details omitted?

**Comment by FredTheHomie** [comment]
$config = [
    'domain_cotrollers' => [''],
    'base_dn'           => '',
    'admin_username'    => '',
    'admin_password'    => '',
    'port'              => 636,
];

**Comment by stevebauman** [comment]
In the above configuration array you've shown, you missed `domain_controllers`, and I noticed you fixed this in the second post here. Can you make sure there's no spelling issues in your actual code? Otherwise it will throw this error

**Comment by FredTheHomie** [comment]
There are currently no spelling issues in my code. I don't understand what I could be doing wrong

**Comment by JakeHump** [comment]
I am having this problem as well.  Did you figure this out?

**Comment by JakeHump** [comment]
Just to point out, I think you should be saying:
$config = [
    'default' = [
        'domain_controllers' => [''],
        'base_dn' => '',
        'admin_username' => '',
        'admin_password' => '',
        'port' => 636,
    ]
];

That should solve the Option 0 error, but it will then become Option 'default' does not exist, so I am not sure it is much better.

**Comment by stevebauman** [comment]
@JakeHump That's incorrect, that's when using the Laravel implementation inside the actual config file.

@FredTheHomie You're setting the configuration incorrectly. The errors aren't lying to you. The option `0` does not exist. You're setting a option incorrectly.

Can you both post your configuration without the username / password?

**Comment by JakeHump** [comment]
Steve, thanks for taking a look at what I'm sure is my misunderstanding of the interactions between the laravel package and the main package.  

I found this cool site that has a public ldap server (read only) that allows you to test your connection without being worried about your personal enterprise environment or credentials: https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server .  I verified with some basic PHP that I can connect to it, but not using your package that I really would prefer to use. Because of this I will post with the information embedded, which should help you see exactly what I'm up to, and hopefully where I am making a mistake.  To be clear, I am using Laravel 5.4, PHP 7, and trying to use the Laravel adldap2 package.   

This is my basic php that proves the connection works:
  # https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
  # https://stackoverflow.com/questions/21628764/ldap-bind-unable-to-bind-to-server-invalid-dn-syntax
    $ldaphost = "ldap.forumsys.com";
    $ldapport = 389;

    $ds = ldap_connect($ldaphost, $ldapport) or die("Could not connect to $ldaphost");
    if ($ds) {
         $username = "newton";
         $upasswd = "password";
         $binddn = "cn=read-only-admin,dc=example,dc=com"; //cn=admin or whatever you use to login by phpldapadmin
         $ldapbind = ldap_bind($ds,$binddn, $upasswd);

         //check if ldap was sucessful
         if ($ldapbind) {
            echo "LDAP bind successful...";
         } else {
            echo "LDAP bind failed...";
         }
    }

Ok, here are the basics of my attempt in Laravel that does not work:

My .env file:

ADLDAP_CONTROLLERS=ldap.forumsys.com
ADLDAP_BASEDN=dc=example,dc=com
ADLDAP_ADMIN_USERNAME=newton
ADLDAP_ADMIN_PASSWORD=password

My adldap.php is mostly defaults, but here it is:
<?php
return [
    'connections' => [
            'default' => [
                'auto_connect' => false,
                'connection' => Adldap\Connections\Ldap::class,
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'connection_settings' => [
                        'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                        'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                        'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '')),
                        'port' => env('ADLDAP_PORT', 389),
                        'timeout' => env('ADLDAP_TIMEOUT', 5),
                        'base_dn' => env('ADLDAP_BASEDN', ''),
                        'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                        'admin_username' => env('ADLDAP_ADMIN_USERNAME', 'username'),
                        'admin_password' => env('ADLDAP_ADMIN_PASSWORD', 'password'),
                        'follow_referrals' => false,
                        'use_ssl' => false,
                        'use_tls' => false,
                ],
        ],
    ],
];

My adldap_auth.php -- as you can see I am trying to use the username (samaccountname) for logging in: 
<?php

return [
    'connection' => env('ADLDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'rules' => [

        // Denys deleted users from authenticating.

        Adldap\Laravel\Validation\Rules\DenyTrashed::class,

        // Allows only manually imported users to authenticate.

        // Adldap\Laravel\Validation\Rules\OnlyImported::class,

    ],
    'scopes' => [

        // Only allows users with a user principal name to authenticate.

        Adldap\Laravel\Scopes\UpnScope::class,

    ],

    'usernames' => [
        'ldap' => 'samaccountname',
        'eloquent' => 'username',
    ],

    'login_fallback' => env('ADLDAP_LOGIN_FALLBACK', true),
    'password_sync' => env('ADLDAP_PASSWORD_SYNC', true),
    'windows_auth_attribute' => ['samaccountname' => 'AUTH_USER'],
    'sync_attributes' => [

        'username' => 'samaccountname',
        'GivenName' => 'GivenName',
        'Surname' => 'Surname'

    ],

];

In the auth.php, I made one change and everything else is default (but since I set login fallback to true, I think this is negligible anyhow) :

    'providers' => [
        'users' => [
            'driver' => 'adldap', // Changed from 'eloquent'
            'model' => App\User::class,
          ],
      ],

In my LoginController.php, I added the following functon:
    public function username()
    {
        return 'username';
    }

In my UserController.php, I do this:
public function setLDAP(Request $request)
    {
      // Create the configuration array.
      $config = [
           'default' =>  [  // Mandatory Configuration Options
                    'domain_controllers'    => 'ldap.forumsys.com',
                    'base_dn'               => 'dc=example,dc=com',
                    'admin_username'        => 'einstein',
                    'admin_password'        => 'password',

                    // Optional Configuration Options
                    'account_prefix'        => '',
                    'account_suffix'        => '',
                    'admin_account_prefix'  => '',
                    'admin_account_suffix'  => '',
                    'port'                  => 389,
                    'follow_referrals'      => false,
                    'use_ssl'               => false,
                    'use_tls'               => false,
                    'timeout'               => 60,

                    // Custom LDAP Options
                    'custom_options'        => [
                        // See: http://php.net/ldap_set_option
                        // LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD
                                                ]
                        ]
                  ];

        // Create a new Adldap Provider instance.
        $provider = new \Adldap\Connections\Provider($config);

        $ad = new \Adldap\Adldap($config);
        try {
                // Connect to the provider you specified in your configuration.
                $provider = $ad->connect('default');

                // Connection was successful.

                // We can now perform operations on the connection.
                $users = $provider->search()->users()->find('newton');
                dd($users);
            } catch (\Adldap\Auth\BindException $e) {
                die("Can't connect / bind to the LDAP server! Error: $e");
                }
    }


I really appreciate you taking a look at it, as I know you really don't have to.  I have put countless hours into this, and refuse to give up.  I hope you can explain what is obvious that I am missing.

**Comment by cryogenx** [comment]
having the same issue cant for the life of me...

**Comment by JakeHump** [comment]
Anybody figure it out?

**Comment by JakeHump** [comment]
Could somebody suggest another package that may work for me?  I was really hoping to use this one, but it seems this issue has stumped the experts.  I am basically looking for an AD package that I can pass authentication through.  My entire process could be read only.  I am already past my deadline and need to take action.  I was really hopeful about this package, but I guess I need to move on.

**Comment by stevebauman** [comment]
@JakeHump Sorry it's not working out so well! Please understand that offering a package that is compatible with various LDAP installation types is difficult, and therefore requires a larger amount of time to configure correctly due to all the options available.

According to your configuration above, you're trying to use the public OpenLDAP server, however your schema is set to `Adldap\Schemas\ActiveDirectory`. You will need to switch this to `Adldap\Schemas\OpenLDAP`

Your `ldap` username is also incorrect for `OpenLDAP`. You will need to use the attribute `dn`, which stands for `distinguished name`. The full distinguished name is used for authentication by OpenLDAP.

By default, the package is set out to use `ActiveDirectory`, so all of the configuration options are set in favor of this type of LDAP installation.

Your `admin_username` and `admin_password` are also incorrect for this public OpenLDAP sever.

You will need to utilize the configuration options `account_prefix` and `account_suffix` to correctly authenticate users by their distinguished name:

```php
'account_prefix' => 'cn=',
'account_suffix' => ',dc=example,dc=com',
```

All these options do, is append a prefix and suffix onto accounts you're authenticating with.

For example, if I'm using `newton` as my username to login, the username that will be used to bind to the LDAP server will be `cn=newton,dc=example,dc=com`.

Keep in mind, OpenLDAP support is experimental right now, but has more support in the `master` branch, and will be released soon with more documentation.

In your `UserController.php`, this is incorrect usage if you're using the Laravel package, since configuration is done inside the configuration files that are published (`config/adldap.php`, `config/adldap_auth.php`).

I'm also not sure what this `UserController` is supposed to achieve. If you're just trying to retrieve an LDAP user, you would do so like this in Laravel:

```php
use Adldap\Laravel\Facades\Adldap;

class UserController extends Controller
{
    public function index()
    { 
        $users = Adldap::search()->users()->get();

        return view('users.index', ['users' => $users]);
    }
}
```

**Comment by JakeHump** [comment]
Thanks for taking a look.  I am actually trying to use Active Directory and can not use OpenLDAP in my organization.  Can you point out what part of my configuration is trying to use OpenLDAP?  That must be my issue.  I was trying very hard to stick to as many of the defaults as possible.  The only thing I wanted to change was login by username instead of email.  Everything else was supposed to be default.  

My attempt in the UserController is simply to configure the connection settings.  Otherwise, how does it know?

**Comment by stevebauman** [comment]
> Can you point out what part of my configuration is trying to use OpenLDAP?

You mentioned here you were using a public LDAP server to test connectivity:

> I found this cool site that has a public ldap server (read only) that allows you to test your connection without being worried about your personal enterprise environment or credentials: https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server .

This public LDAP server is using OpenLDAP, not ActiveDirectory.

> My attempt in the UserController is simply to configure the connection settings. Otherwise, how does it know?

It knows by loading in the configuration via the service provider in the files that are published in your application (`config/adldap.php`).

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/AdldapServiceProvider.php#L41-L60

Have you followed the installation? Also, are you familiar with how Laravel uses configuration files and how to publish them from service providers?

**Comment by JakeHump** [comment]
This is gonna sound crazy, but I have literally re-done the walkthrough like ten different times over the period of the last three months.  I posted above everything I changed from laravel 5.4's default settings..  I always end up doing the exact same things, because it is pretty clear what needs to be done in the walkthrough.  However, I repeatedly get the same two errors:  Invalid credentials and "Option default does not exist."    The option default does not exist is baffling to me as I am so specific about setting it.

I am very familiar with Laravel and have built a number of successful applications using it.  I understand facades and aliases as well as a number of relationships (one-to-many and many-to-many being my primary focus).

This is Laravel's error:
Option default does not exist.
in DomainConfiguration.php (line 116)
--
at DomainConfiguration->get('default')in DomainConfiguration.php (line 147)

**Comment by FredTheHomie** [comment]
I had a similar issue. I was trying to connect at my workplace but using my
own laptop, so for security reasons, I couldn't connect to the server. I
had to manually connect an ethernet cable to my laptop, or use their
laptops. Check the security settings of the AD provider.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=ranj.salih1996@gmail.com&idSignature=22>

**Comment by Albvadi** [comment]
Hi @JakeHump,
you have two problems in your configuration. I replicate all your config and arrive to your problems...

1. **The 'option default' problem.** The Adldap object, need a configuration based on providers (https://github.com/Adldap2/Adldap2/blob/master/src/Adldap.php#L31), but the Provider object itself, needs a root configuration (https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Provider.php#L71), and you are using the same config array for both. So, in your UserController.php, to test, you must change:
    - You can remove the `$provider = new \Adldap\Connections\Provider($config);` because in the following line `$provider = $ad->connect('default');` you are creating the instance too.
    - Or, change `$provider = new \Adldap\Connections\Provider($config);` to `$provider = new \Adldap\Connections\Provider($config['default']);`

2. After the last change, the error says that $domain_controllers must be an array... You must change `'domain_controllers'    => 'ldap.forumsys.com',` to `'domain_controllers'    => ['ldap.forumsys.com'],`

And the last thing, if you test against LDAP, you need to set the Schema to LDAP... just right next to `$provider = $ad->connect('default');` add `$provider->setSchema(new \Adldap\Schemas\OpenLDAP());`

I hope this helps you... :simple_smile:

**Comment by JakeHump** [comment]
Thank you so much!  Those little tweaks have resolved my initial connection issues.    Thanks so much for taking a look!

**Comment by stevebauman** [comment]
Thanks @Albvadi for helping out!

Closing due to inactivity from original author.
