### ISSUE TITLE
Switched to PHP 7.2 from 7.1, now getting fatal error

### ISSUE THREAD

**Issue by dmcconnell68** [Adldap2/Adldap2#566]
Adldap2 Version: 8.0
LDAP Type: Active Directory
PHP Version: 7.1

### Description:
Upgraded PHP to 7.2 because of an issue with bit datatype in MySQL.  Now I'm getting an undefined function fatal error.  Any ideas?

php_error.log
[25-Jul-2018 21:23:06 America/Tegucigalpa] PHP Warning:  Use of undefined constant LDAP_OPT_PROTOCOL_VERSION - assumed 'LDAP_OPT_PROTOCOL_VERSION' (this will throw an Error in a future version of PHP) in D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php on line 252
[25-Jul-2018 21:23:06 America/Tegucigalpa] PHP Warning:  Use of undefined constant LDAP_OPT_NETWORK_TIMEOUT - assumed 'LDAP_OPT_NETWORK_TIMEOUT' (this will throw an Error in a future version of PHP) in D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php on line 253
[25-Jul-2018 21:23:06 America/Tegucigalpa] PHP Warning:  Use of undefined constant LDAP_OPT_REFERRALS - assumed 'LDAP_OPT_REFERRALS' (this will throw an Error in a future version of PHP) in D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php on line 254
[25-Jul-2018 21:23:06 America/Tegucigalpa] PHP Fatal error:  Uncaught Error: Call to undefined function Adldap\Connections\ldap_set_option() in D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Ldap.php:183
Stack trace:
#0 D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Ldap.php(192): Adldap\Connections\Ldap->setOption('LDAP_OPT_PROTOC...', 3)
#1 D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php(258): Adldap\Connections\Ldap->setOptions(Array)
#2 D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php(109): Adldap\Connections\Provider->prepareConnection()
#3 D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Provider.php(59): Adldap\Connections\Provider->setConnection(NULL)
#4 D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Adldap.php(48): Adldap\Connections\Provider->__construct(Array, NULL, NULL)
#5 D:\inetpub\wwwroot\stsportaldevnew\public\authenticate.php(29): Adldap\Adldap->addProvider(Array)
#6 D:\inetpub\wwwro in D:\inetpub\wwwroot\stsportaldevnew\vendor\adldap2\adldap2\src\Connections\Ldap.php on line 183

**Comment by stevebauman** [comment]
Hi @dmcconnell68,

It appears you don’t have the LDAP extension enabled with that version of PHP. Enable it and you won’t receive any exceptions.

**Comment by jakelowie** [comment]
Hi , I have enabled already the php extension but it still throws the same error . I don't know what to do anymore . 

![image](https://user-images.githubusercontent.com/46545502/71155858-a43bef80-2279-11ea-9648-0c494f70234b.png)

This is the error that it throws .

![image](https://user-images.githubusercontent.com/46545502/71155875-b61d9280-2279-11ea-909f-75d22519ea35.png)
