### ISSUE TITLE
could't add a value to empty field.

### ISSUE THREAD

**Issue by noname007** [Adldap2/Adldap2#582]
- Adldap2 Version: #.#
- LDAP Type: Active Directory
- PHP Version: v9.0.1

### Description:

Updating the title field  when i call user model `save()` function,  throw exception， and this field is empty，no any character(such as white space)。

 Using yii2 framework function 
` \Yii::info($user->getModifications());` 
output the value :

```
2018-09-07 14:40:29 [-][-][-][info][application] [
    [
        'attrib' => 'title',
        'modtype' => 1,
        'values' => [
            '主管',
        ],
    ],
]
```

```

PHP Warning 'yii\base\ErrorException' with message 'ldap_modify_batch(): Batch Modify: Type or value exists'

in vendor/adldap2/adldap2/src/Connections/Ldap.php:327

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'ldap_modify_bat...', '/Users/yangzhen...', 327, Array)
#1 vendor/adldap2/adldap2/src/Connections/Ldap.php(327): ldap_modify_batch(Resource id #75, 'cn=\xE5\xBC\xA0\xE4\xBC\x9F\xE7\xBA\xA2(20...', Array)
#2 vendor/adldap2/adldap2/src/Models/Model.php(818): Adldap\Connections\Ldap->modifyBatch('cn=\xE5\xBC\xA0\xE4\xBC\x9F\xE7\xBA\xA2(20...', Array)
#3 vendor/adldap2/adldap2/src/Models/Model.php(800): Adldap\Models\Model->update(Array)

```

**Comment by stevebauman** [comment]
Hi @noname007,

Can you post your code?

**Comment by noname007** [comment]
```
           $user = $search->findBy('pager', $usercode);

            $user_cn = "cn=$name($usercode)";
            $user_dn = "$user_cn,$dn";

            if(!$user) {
                $user =  $search->findByDn($user_dn);
                if(!$user) {
                    $user = $provider->make()->user();
//                    $user->setAttribute($scheme->unicodePassword(), Utilities::encodePassword('inipassword'));
                }
            }else{
                $old_user_dn = $user->getDistinguishedName();
                if($old_user_dn != $user_dn) {
                    $user->move($user_cn, $dn);
                    \Yii::warning('change dn:'.$user_dn);
                }
            }

            \Yii::info($user->exists);
            \Yii::info($user->getAttributes());



            $user->setDistinguishedName($user_dn);
            $user->setAccountName($account);
            $user->setUserPrincipalName( $account);
            $user->setDisplayName($name);
            $user->setDepartment(substr(implode('-', $org_arr), 0, 64));
            $user->setUserAccountControl($useraccountcontrol);
            $user->setTitle($title);
            $user->fill([
                'pager' => $usercode,
                'extensionAttribute3' => (strlen((string)$usercode) != 5 || $companycode == 'JX0981') ? 1 : 0, // 0 开通邮箱，1 关闭邮箱
                'mobile' => $mobile,
                $scheme->objectClass() => self::OBJECT_CLASS[get_class($user)],
                'extensionAttribute2' => $mail_domain,
            ]);

            \Yii::info($user->getModifications());
            \Yii::info($user->getDirty());
            \Yii::getLogger()->flush();

//            if($user->exists) {
//                $user->getQuery()->getConnection()->modify($user->getDn(), $user->getDirty());
 //           }else{
  //              $user->create();
   //         }

           $user->save();
```

**Comment by noname007** [comment]
a part of code of

**Comment by stevebauman** [comment]
Where does the `$title` variable come from? What is its value?

I don't think the exception you see is coming from setting the `title`, its coming from another attribute.

**Comment by noname007** [comment]
$title value is a chinese word “主管”

**Comment by stevebauman** [comment]
Okay so you're filling out the value, but you mentioned that the field is empty when you try to save it?

> Updating the **title** field when i call user model save() function, throw exception， and this field is empty，no any character(such as white space)。

You're performing a quite a few operations in the code you've pasted above, so the exception you're receiving could occur from many places.

It's likely that you're getting this from this:

```php
$user->fill([
    'pager' => $usercode,
    'extensionAttribute3' => (strlen((string)$usercode) != 5 || $companycode == 'JX0981') ? 1 : 0, // 0 开通邮箱，1 关闭邮箱
    'mobile' => $mobile,
    $scheme->objectClass() => self::OBJECT_CLASS[get_class($user)], // <-- This line here
    'extensionAttribute2' => $mail_domain,
]);
```

You're setting the `objectClass` of the user to the PHP class name of the `$user` object?

I would try cutting down the amount of operations going on here so we can track down which attribute it's failing on...

**Comment by noname007** [comment]
@stevebauman 

Instead of save() by  using the  below code , it was success

```
//            if($user->exists) {
//                $user->getQuery()->getConnection()->modify($user->getDn(), $user->getDirty());
 //           }else{
  //              $user->create();
   //         }
```

**Comment by noname007** [comment]
`$scheme->objectClass() ` was guaranteed to have the right value by the outter code that i not paste here
