### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by NurPech** [Adldap2/Adldap2#666]
- Adldap2 Version: don't know maybe 5.*
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:
I want to use firefly iii which is using adldap2 for ldap authentication. As this is not working and the issue seems to be related to adldap2, I had created this issue.

The ldap bind is not successfully:

ext Adldap\Auth\BindException: Invalid credentials in /opt/firefly-iii/vendor/adldap2/adldap2/src/Auth/Guard.php:109
Stack trace:
#0 /opt/firefly-iii/vendor/adldap2/adldap2/src/Auth/Guard.php(121): Adldap\Auth\Guard->bind('CN=ldap_bind,OU...', 'XXXX...')
#1 /opt/firefly-iii/vendor/adldap2/adldap2/src/Connections/Provider.php(234): Adldap\Auth\Guard->bindAsAdministrator()

### Steps To Reproduce:
These are the config values regarding adldap2:
ADLDAP_CONTROLLERS="192.168.xxx.11"
ADLDAP_PORT=389
ADLDAP_TIMEOUT=5
ADLDAP_BASEDN="dc=g*******,dc=local"
ADLDAP_FOLLOW_REFFERALS=false
ADLDAP_USE_SSL=false
ADLDAP_USE_TLS=false

ADLDAP_ADMIN_USERNAME="CN=ldap_bind,OU=Benutzer,OU=G*******,DC=g*******,DC=local"
ADLDAP_ADMIN_PASSWORD="XXXX"

_____________________________________________
The admin user and password a definitly correct.
Could you assist me with the issue?

**Comment by stevebauman** [comment]
Hi @NurPech,

Your LDAP server is saying your credentials are invalid.

Have you validated that the distinguished name of the username you're trying to bind with is 100% correct as well as your password? A space or incorrect character could be the cause:

```
CN=ldap_bind,OU=Benutzer,OU=G*******,DC=g*******,DC=local
```

Since you're using AD, you could also try using a user principal name instead of a distinguished name for the binding username such as `ldap_bind@domain.local`.

Let me know how it goes and I can continue helping you get up and running :smile:

**Comment by NurPech** [comment]
Hi @stevebauman 

Yes, I have copied the distinguished name from the attribute editor to the config file. Also I have double checked the password.

I've also tried to use the user principal name, with same issue.

The native function of php (ldap_bind) ist working like a charm. So it must be a issue within adldap in my opinion. Is there any way to do further debugging?

**Comment by stevebauman** [comment]
Have you set a prefix or suffix in your configuration? Can you post your `ldap.php` and ldap_auth.php` files with any sensitive details omitted?

**Comment by poseidonphp** [comment]
FWIW - I was upgrading from version 7 to version 10, and ran into the same issue. Mine was because in version 7 of the config, there was an "admin_account_suffix" key. Version 10 config doesn't appear to have (or support) that key, so i had to add the suffix to the username that is used for binding.
The account suffix key in the config was working properly for users attempting to authenticate, just the binding account needed to have the suffix hard coded. Please correct me if i've mis-stated anything here, but this got it working for me.

**Comment by kunli0** [comment]
> FWIW - I was upgrading from version 7 to version 10, and ran into the same issue. Mine was because in version 7 of the config, there was an "admin_account_suffix" key. Version 10 config doesn't appear to have (or support) that key, so i had to add the suffix to the username that is used for binding.
> The account suffix key in the config was working properly for users attempting to authenticate, just the binding account needed to have the suffix hard coded. Please correct me if i've mis-stated anything here, but this got it working for me.

I just had the same problem when started a new project. I was previously using v8.0.0 which provided the admin account suffix option.

**Comment by rakashpal** [comment]
I am facing same problem with adldap2-laravel package.I have also followed above listed solution. But problem remain same
